export interface Review {
  curator: string;
  date: string;
  rating: number;
  comment: string;
}

export interface ItemData {
  id: string;
  title: string;
  desc: string;
  price: string;
  priceValue: number;
  delay: string;
  img: string;
  category: "all" | "jewelry" | "couture" | "galerie" | "living" | "essence" | "horology" | "cellar" | "other" | "curated";
  longDesc: string;
  craftTitle: string;
  craftP1: string;
  craftP2: string;
  rating: number;
  reviewCount: number;
  soldCount: number;
  reviews: Review[];
}

export const ATELIER_ITEMS: ItemData[] = [
  {
    id: "archetype-vessel",
    title: "The Archetype Sculptural Vessel",
    desc: "Volcanic Clay, Matte Finish",
    price: "₱ 74,400",
    priceValue: 74400,
    delay: "",
    img: "/assets/items/archetype-vessel.jpg",
    category: "galerie",
    longDesc: "A singular exploration of form and void. Each vessel is hand-thrown in our mountain atelier, finished with a raw volcanic slip that captures the essence of tectonic movement.",
    craftTitle: "Philosophical Craft",
    craftP1: "Our process begins with the earth itself. We source clays that contain high iron content, resulting in a unique patina that develops character over decades of use.",
    craftP2: "The Archetype series is inspired by Brutalist architecture and the Japanese concept of Ma—the space between. It is not just a container, but a sculptural presence that anchors a room.",
    rating: 4.9,
    reviewCount: 12,
    soldCount: 84,
    reviews: [
      { curator: "Cassian V.", date: "March 12, 2026", rating: 5, comment: "The matte volcanic finish is even more profound in person. It perfectly captures the tectonic presence I was seeking for my study." },
      { curator: "Elena R.", date: "February 28, 2026", rating: 4.8, comment: "A masterpiece of restraint. The weight and texture are unmistakably authentic." }
    ]
  },
  {
    id: "item-01",
    title: "Ethereal Form No. 01",
    desc: "Handcrafted Ceramic",
    price: "₱ 20,400",
    priceValue: 20400,
    delay: "",
    img: "/assets/items/ethereal-ceramic-form.jpg",
    category: "galerie",
    longDesc: "A singular exploration of form and void. Each bespoke piece is finished with distinct architectural geometry capturing the essence of tectonic movement.",
    craftTitle: "Philosophical Craft",
    craftP1: "Our process begins with the earth itself. We design with intent, resulting in a unique patina that develops character over decades of use.",
    craftP2: "The collection is inspired by Brutalist architecture and the Japanese concept of Ma—the space between. It is not just an object, but a sculptural presence that anchors a room.",
    rating: 4.7,
    reviewCount: 8,
    soldCount: 42,
    reviews: [
      { curator: "Julian S.", date: "January 15, 2026", rating: 5, comment: "The geometric precision is breathtaking. It integrates seamlessly into my minimalist galerie." }
    ]
  },
  {
    id: "item-02",
    title: "Orbital Brass Luminary",
    desc: "Brushed Brass & Glass",
    price: "₱ 53,400",
    priceValue: 53400,
    delay: "md:mt-24",
    img: "/assets/items/orbital-brass-luminary.jpg",
    category: "other",
    longDesc: "Illumination as an art form. The Orbital Luminary utilizes geometric refraction to cast a warm, ambient glow that adapts to the mood of any modernist space.",
    craftTitle: "Casting Light",
    craftP1: "Machined from solid brass billets, the luminary undergoes a rigorous hand-brushing process that produces a subtle, matte luster.",
    craftP2: "By marrying industrial precision with blown opal glass, the fixture becomes a timeless statement piece that honors both engineering and organic warmth.",
    rating: 4.8,
    reviewCount: 24,
    soldCount: 156,
    reviews: [
      { curator: "Marcus T.", date: "March 05, 2026", rating: 5, comment: "The ambient diffusion is peerless. It transforms the atmosphere of the room instantly." }
    ]
  },
  {
    id: "item-03",
    title: "Solis Lounge Chair",
    desc: "Oak & Performance Wool",
    price: "₱ 75,000",
    priceValue: 75000,
    delay: "",
    img: "/assets/items/solis-lounge-chair.jpg",
    category: "living",
    longDesc: "Ergonomics meets profound minimalism. The Solis Lounge Chair embraces the sitter with an intuitive recline, floating upon a stark oak framework.",
    craftTitle: "Structural Harmony",
    craftP1: "Each oak beam is selected for its grain pattern, kiln-dried, and joined using seamless mortise and tenon techniques developed in our European workshop.",
    craftP2: "The cushions are tailored from sustainable performance wool that resists wear while providing a tactile, sensory luxury unmatched in modern furniture design.",
    rating: 4.9,
    reviewCount: 15,
    soldCount: 52,
    reviews: []
  },
  {
    id: "item-04",
    title: "Silent Stone Vessel",
    desc: "Travertine Stone",
    price: "₱ 10,800",
    priceValue: 10800,
    delay: "md:mt-24",
    img: "/assets/items/travertine-stone-vessel.jpg",
    category: "other",
    longDesc: "Carved from a single block of raw travertine, this vessel strips away the unnecessary, leaving only the pure, porous texture of geological history.",
    craftTitle: "Geological Preservation",
    craftP1: "We source our travertine from dormant quarries, ensuring that the natural veining and textural voids are preserved perfectly in the carving process.",
    craftP2: "The vessel serves not merely as a container, but as an artifact. It grounds the modern home by bringing raw, untreated nature indoors.",
    rating: 4.8,
    reviewCount: 6,
    soldCount: 14,
    reviews: []
  },
  {
    id: "item-05",
    title: "Monolith Chair",
    desc: "Ebonized Ash Wood",
    price: "₱ 288,000",
    priceValue: 288000,
    delay: "",
    img: "/assets/items/monolith-ash-chair.jpg",
    category: "living",
    longDesc: "A striking silhouette designed to dominate space. The Monolith Chair balances brutalist aesthetic intensity with surprising anatomical comfort.",
    craftTitle: "The Dark Finish",
    craftP1: "The signature charcoal hue is achieved through an ancient ebonization process. We treat the ash wood with an iron-oxide solution that reacts with natural tannins.",
    craftP2: "The result is a light-absorbing, matte black finish that completely exposes the sweeping wood grain beneath, a testament to high-contrast design.",
    rating: 4.9,
    reviewCount: 3,
    soldCount: 8,
    reviews: []
  },
  {
    id: "item-06",
    title: "Brass Pendant Light",
    desc: "Aged Brass & Opal Glass",
    price: "₱ 51,000",
    priceValue: 51000,
    delay: "md:mt-24",
    img: "/assets/items/brass-pendant-light.jpg",
    category: "other",
    longDesc: "Suspended elegance. This pendant light serves as a focal point over dining spaces, merging industrial hardware with classic glassblowing techniques.",
    craftTitle: "Suspension Art",
    craftP1: "The brass housing is aged gracefully using an accelerated oxidation bath, ensuring no two pendants share the exact same microscopic patina.",
    craftP2: "When illuminated, the opal glass sphere diffuses harsh light into a soothing aura, creating an atmosphere of sophisticated intimacy.",
    rating: 4.7,
    reviewCount: 18,
    soldCount: 92,
    reviews: []
  },
  {
    id: "item-07",
    title: "Ebony Plinth",
    desc: "Solid Ebony Wood",
    price: "₱ 66,000",
    priceValue: 66000,
    delay: "",
    img: "/assets/items/ebony-plinth.jpg",
    category: "living",
    longDesc: "A masterclass in restraint. This display plinth elevates any object placed upon it, serving as a reverent pedestal for art, plants, or literature.",
    craftTitle: "Elevating Context",
    craftP1: "Crafted from ethically sourced, solid ebony, the plinth's sheer density and weight provide a structural anchor for precarious curation.",
    craftP2: "The unadorned geometry ensures the plinth never competes with the object it holds; rather, it commands attention through subtle, monolithic presence.",
    rating: 4.9,
    reviewCount: 5,
    soldCount: 12,
    reviews: []
  },
  {
    id: "item-08",
    title: "Archetype Vessel Detail",
    desc: "Glazed Finish",
    price: "₱ 38,400",
    priceValue: 38400,
    delay: "md:mt-24",
    img: "/assets/items/vessel-surface-detail.jpg",
    category: "galerie",
    longDesc: "A micro-study in ceramics. This scaled-down archetype focuses on surface tension, utilizing a high-gloss glaze that breaks beautifully over raw edges.",
    craftTitle: "Chemistry of Glaze",
    craftP1: "We developed a proprietary silicate glaze that intentionally crackles during the cooling process, creating microscopic valleys of texture.",
    craftP2: "When caught in the daylight, the surface reflects a spectrum of dormant tones, proving that profound beauty rests in the smallest details.",
    rating: 4.8,
    reviewCount: 9,
    soldCount: 34,
    reviews: []
  },
  {
    id: "item-09",
    title: "Gilded Silk Carré",
    desc: "Edition No. 42 • Saffron",
    price: "₱ 25,200",
    priceValue: 25200,
    delay: "",
    img: "/assets/items/silk-carre-saffron.jpg",
    category: "couture",
    longDesc: "Woven from mulberry silk and edged with hand-rolled hems, the Gilded Carré serves as a vibrant, tactile accessory for the modern silhouette.",
    craftTitle: "Textile Legacy",
    craftP1: "Printed using traditional serigraphy techniques in Lyon, the chromatic depth of the Saffron dye is unparalleled in modern synthetic printing.",
    craftP2: "Every scarf takes over 200 hours to complete, passing through the hands of artisan colorists before being numbered in its limited edition.",
    rating: 5.0,
    reviewCount: 21,
    soldCount: 112,
    reviews: []
  },
  {
    id: "item-10",
    title: "Nightshade Silk Gown",
    desc: "Habotai Silk • Midnight",
    price: "₱ 270,000",
    priceValue: 270000,
    delay: "md:mt-24",
    img: "/assets/items/nightshade-silk-gown.jpg",
    category: "couture",
    longDesc: "Fluidity in motion. This bias-cut gown cascades down the body like liquid midnight, utilizing the natural shimmer of high-density silk.",
    craftTitle: "The Bias Cut",
    craftP1: "Cutting silk on the 45-degree angle allows the fabric to stretch and drape without losing its structural integrity. It is an art of extreme wastage and extreme beauty.",
    craftP2: "Each gown is hemmed by hand, a process that takes two artisans full days to complete, resulting in a weightless, invisible edge.",
    rating: 4.9,
    reviewCount: 7,
    soldCount: 19,
    reviews: []
  },
  {
    id: "item-11",
    title: "Chronos VII Galerie",
    desc: "Horology • Limited Edition",
    price: "₱ 534,000",
    priceValue: 534000,
    delay: "",
    img: "/assets/items/chronos-skeletonized.jpg",
    category: "horology",
    longDesc: "A mechanical masterpiece. The Chronos VII is a masterwork in micromechanics, featuring a skeletonized dial that exposes the beating heart of the escapement.",
    craftTitle: "Mastering Time",
    craftP1: "Our horologists assemble the 312 individual components under a microscope. The tourbillon carriage alone takes three days to balance perfectly.",
    craftP2: "Encased in brushed titanium and secured with a hand-stitched alligator strap, this timepiece transcends mere function to become a wearable galerie of human ingenuity.",
    rating: 5.0,
    reviewCount: 2,
    soldCount: 4,
    reviews: []
  },
  {
    id: "item-12",
    title: "The Serene Carryall",
    desc: "Leather • Sandstone",
    price: "₱ 85,200",
    priceValue: 85200,
    delay: "md:mt-24",
    img: "/assets/items/serene-carryall.jpg",
    category: "couture",
    longDesc: "Designed for the nomadic curator. This expansive carryall merges structured geometry with the organic drape of full-grain calfskin luggage.",
    craftTitle: "Saddle Architecture",
    craftP1: "Utilizing heritage saddle-stitching techniques, craftsmen sew the expansive panels using waxed thread that swells to fill the punctured leather, creating a waterproof seal.",
    craftP2: "The unlined interior showcases the pure sueded back of the hide, leaning into a philosophy of transparent, honest luxury.",
    rating: 4.8,
    reviewCount: 12,
    soldCount: 64,
    reviews: []
  },
  {
    id: "jewelry-01",
    title: "Tectonic Gold Cuff",
    desc: "18k Recycled Gold",
    price: "₱ 228,000",
    priceValue: 228000,
    delay: "",
    img: "/assets/items/tectonic-gold-cuff.jpg",
    category: "jewelry",
    longDesc: "A statement of geological permanence. The Tectonic Cuff is hand-hammered to create a surface that mimics the raw movement of the earth's crust.",
    craftTitle: "Forged Alignment",
    craftP1: "Each cuff is forged from a single bar of solid gold. Over 4,000 individual hammer strikes are required to achieve the signature undulating texture.",
    craftP2: "The interior is polished to a mirror finish, providing a secret, smooth comfort against the skin that contrasts with the rugged exterior.",
    rating: 4.9,
    reviewCount: 14,
    soldCount: 28,
    reviews: []
  },
  {
    id: "jewelry-02",
    title: "Orbital Pearl Earrings",
    desc: "South Sea Pearls & Platinum",
    price: "₱ 132,000",
    priceValue: 132000,
    delay: "md:mt-24",
    img: "/assets/items/orbital-pearl-earrings.jpg",
    category: "jewelry",
    longDesc: "Celestial symmetry. These floating South Sea pearls are suspended within a fine platinum orbit, creating a look of effortless weightlessness.",
    craftTitle: "Suspended Luster",
    craftP1: "We source only 'AAA' grade pearls from sustainable farms in the South Pacific, ensuring a flawless skin and deep, iridescent orient.",
    craftP2: "The platinum wire is cold-worked to maintain its tension, allowing the pearls to rotate freely as if governed by a private gravity.",
    rating: 4.8,
    reviewCount: 11,
    soldCount: 42,
    reviews: []
  },
  {
    id: "horology-01",
    title: "Astrum Moonphase",
    desc: "Rose Gold • Avant-Garde",
    price: "₱ 744,000",
    priceValue: 744000,
    delay: "",
    img: "/assets/items/astrum-moonphase.jpg",
    category: "horology",
    longDesc: "A cosmic tracking engine. The Astrum features a hyper-accurate moonphase complication that only requires adjustment once every 122 years.",
    craftTitle: "Celestial Mechanics",
    craftP1: "The moon disc is crafted from a slice of Gibeon meteorite, featuring its natural Widmanstätten pattern for an authentic lunar texture.",
    craftP2: "Beneath the dial, a proprietary caliber 842-M beats at 28,800 vibrations per hour, a silent testament to the absolute mastery of time.",
    rating: 4.9,
    reviewCount: 4,
    soldCount: 9,
    reviews: []
  },
  {
    id: "horology-02",
    title: "Eclipse Chronograph",
    desc: "Titanium • Stealth Matte",
    price: "₱ 576,000",
    priceValue: 576000,
    delay: "md:mt-24",
    img: "/assets/items/eclipse-chronograph.jpg",
    category: "horology",
    longDesc: "Performance meets stealth. The Eclipse is housed in a Grade 5 titanium case with a black DLC coating, designed for maximum durability and zero reflection.",
    craftTitle: "Industrial Precision",
    craftP1: "The column-wheel chronograph movement ensures a crisp, tactile click when engaging the stopwatch function, a favorite of dedicated horological enthusiasts.",
    craftP2: "The rubber strap is integrated seamlessly into the lugs, creating a continuous bridge from watch to wrist for unparalleled ergonomic comfort.",
    rating: 4.7,
    reviewCount: 22,
    soldCount: 88,
    reviews: []
  },
  {
    id: "living-01",
    title: "Petal Side Table",
    desc: "Carrara Marble & Steel",
    price: "₱ 111,000",
    priceValue: 111000,
    delay: "",
    img: "/assets/items/petal-side-table.jpg",
    category: "living",
    longDesc: "A delicate balance of materials. Three steel 'petals' support a cantilevered slab of Carrara marble, creating a focal point of geometric elegance.",
    craftTitle: "Material Weightlessness",
    craftP1: "We utilize advanced structural engineering to ensure the table remains perfectly stable despite its impossibly thin supports.",
    craftP2: "The marble is honed rather than polished, preserving the cool, tactile texture of the stone while highlighting the subtle grey veining.",
    rating: 4.8,
    reviewCount: 15,
    soldCount: 56,
    reviews: []
  },
  {
    id: "living-02",
    title: "Monolithic Coffee Table",
    desc: "Solid Walnut • Natural Oil",
    price: "₱ 234,000",
    priceValue: 234000,
    delay: "md:mt-24",
    img: "/assets/items/monolithic-coffee-table.jpg",
    category: "living",
    longDesc: "Substantial, grounded luxury. This coffee table is carved from three massive planks of American walnut, celebrating the raw, uncut power of the forest.",
    craftTitle: "Arboreal Mastery",
    craftP1: "The wood is air-dried for two years before finishing, ensuring it will never warp or crack, even in the most demanding home environments.",
    craftP2: "We use a multi-stage oiling process that penetrates deep into the grain, protecting the timber while allowing it to breathe and develop a rich patina.",
    rating: 4.9,
    reviewCount: 8,
    soldCount: 31,
    reviews: []
  },
  {
    id: "essence-01",
    title: "Mist of the Highlands",
    desc: "Eau de Parfum • 50ml",
    price: "₱ 11,100",
    priceValue: 11100,
    delay: "",
    img: "/assets/items/highland-mist-essence.jpg",
    category: "essence",
    longDesc: "Atmospheric and ethereal. This fragrance captures the scent of cold morning dew upon heather and granite, a truly transportive olfactive experience.",
    craftTitle: "Extracting Atmosphere",
    craftP1: "By utilizing CO2 extraction for the botanical nodes, we preserve the most volatile and delicate scent molecules that traditional steam distillation destroys.",
    craftP2: "The result is a prefix-free fragrance of incredible clarity. It doesn't smell like perfume; it smells like a place you've always wanted to go back to.",
    rating: 4.6,
    reviewCount: 19,
    soldCount: 142,
    reviews: []
  },
  {
    id: "essence-02",
    title: "Nocturne Noir Fragrance",
    desc: "Parfum Extract • 30ml",
    price: "₱ 18,600",
    priceValue: 18600,
    delay: "md:mt-24",
    img: "/assets/items/nocturne-noir-parfum.jpg",
    category: "essence",
    longDesc: "Deep, mysterious, addictive. Nocturne Noir is a concentrated extract that centers on rare agarwood, smoke, and black vanilla bean.",
    craftTitle: "The Dark Spectrum",
    craftP1: "Oud is one of the most expensive ingredients in perfumery. We source ours from sustainably infected Aquilaria trees in Assam, India.",
    craftP2: "Because of its high concentration (30%), the fragrance lasts for over 24 hours on the skin, slowly revealing its hidden, resinous depths throughout the night.",
    rating: 4.8,
    reviewCount: 14,
    soldCount: 96,
    reviews: []
  },
  {
    id: "cellar-01",
    title: "Reserve Brut 2012",
    desc: "Vintage Champagne • Reims",
    price: "₱ 27,000",
    priceValue: 27000,
    delay: "",
    img: "/assets/items/reserve-brut-2012.jpg",
    category: "cellar",
    longDesc: "A celebration of a decade. The 2012 vintage is renowned for its incredible balance of acidity and brioche-like depth, a perfect expression of its terroir.",
    craftTitle: "Effervescence of Time",
    craftP1: "Aged for 10 years on the lees in our chalk cellars, the mousse is impossibly fine, creating a creamy texture that is both sharp and comforting.",
    craftP2: "Every bottle is riddled by hand, a heritage technique that ensures absolute clarity without the use of industrial centrifuge equipment.",
    rating: 4.9,
    reviewCount: 12,
    soldCount: 224,
    reviews: []
  },
  {
    id: "cellar-02",
    title: "Single Malt Heritage",
    desc: "Islay • 25 Years Old",
    price: "₱ 108,000",
    priceValue: 108000,
    delay: "md:mt-24",
    img: "/assets/items/islay-single-malt.jpg",
    category: "cellar",
    longDesc: "A quarter-century of peat and salt. This single malt is a heavy, oceanic spirit that has matured in ex-sherry casks within earshot of the Atlantic.",
    craftTitle: "The Cask's Influence",
    craftP1: "We selected a single Oloroso sherry butt for this expression. The resulting spirit is mahogany-dark with notes of dried fruit and medicinal smoke.",
    craftP2: "Bottled at cask strength without chill-filtration, it represents the purest possible presentation of a legendary Islay distillery's house style.",
    rating: 4.9,
    reviewCount: 16,
    soldCount: 54,
    reviews: []
  },
  {
    id: "item-13",
    title: "Soleil d'Or Essence",
    desc: "Fragrance • 100ml",
    price: "₱ 14,700",
    priceValue: 14700,
    delay: "",
    img: "/assets/items/soleil-dor-fragrance.jpg",
    category: "essence",
    longDesc: "An olfactive memory of late summer. Soleil d'Or balances deep amber resins with the fleeting, volatile notes of crushed citrus and dry Mediterranean woods.",
    craftTitle: "Distilling Light",
    craftP1: "Our master perfumers macerate the raw botanicals for over 90 days, allowing the molecular structures to round out and bind into a seamless profile.",
    craftP2: "Bottled in heavy, lead-free crystal, the fragrance interacts dynamically with the skin's chemistry, guaranteeing an impossibly unique signature for every wearer.",
    rating: 4.7,
    reviewCount: 31,
    soldCount: 212,
    reviews: []
  },
  {
    id: "item-14",
    title: "Grand Cru Cellar Box",
    desc: "Curated Vintages",
    price: "₱ 192,000",
    priceValue: 192000,
    delay: "md:mt-24",
    img: "/assets/items/grand-cru-cellar-box.jpg",
    category: "cellar",
    longDesc: "A pinnacle of enology. The Cellar Box contains three exceptionally rare vintages sourced directly from the private reserves of historic European estates.",
    craftTitle: "The Patience of Maturation",
    craftP1: "Wine is the only art that must be consumed to be fully appreciated. We selected these bottles precisely at the apex of their maturity curve.",
    craftP2: "Encased in an atmosphericly controlled, velvet-lined walnut case, the collection guarantees optimal provenance for the most discerning collector.",
    rating: 5.0,
    reviewCount: 1,
    soldCount: 2,
    reviews: []
  }
];
